#lists of genes

#All CD8alpha genes
cd8alpha <- c("LOC107053306",
              "LOC101752184",
              "LOC121110778",
              "LOC121110777",
              "LOC124416945",
              "LOC121110775",
              "LOC121110774",
              "LOC101749090",
              "LOC100858172",
              "LOC771880",
              "LOC100857206",
              "LOC121106511",
              "LOC771798",
              "LOC107049163",
              "LOC121113234",
              "LOC121110779",
              "LOC124417043",
              "LOC100857817",
              "LOC107053308",
              "LOC107049158",
              "LOC121113235",
              "LOC121110776",
              "LOC121106480",
              "LOC121106473",
              "LOC112532337",
              "LOC107053324",
              "LOC107049168",
              "LOC121113232",
              "LOC121110780",
              "LOC771804",
              "LOC124418359",
              "LOC124417056",
              "LOC112532335",
              "LOC107049200",
              "LOC121113233",
              "LOC121110760",
              "LOC121106496")

#markers from shah et al
shah_markers <- c("PAX5",
                  "LOC396098",
                  "LOC419333",
                  #                  "LOC112531844",
                  "BLVRA",
                  "TNFRSF13C",
                  "SCG5",
                  #                  "LOC100857302",
                  "CD1C",
                  "WDR66",
                  "INHBA",
                  "ARHGAP22",
                  "RASGEF1B",
                  "DCLK3",
                  "HTRA1",
                  #                  "CCL4",
                  "CSF1R",
                  #                  "FYB",
                  "FCER1G",
                  "DOCK4",
                  "TCF7",
                  "BCL11B",
                  #                  "CNKSR2L",
                  "RORA",
                  "CTLA4",
                  "UBASH3A",
                  "TOX2",
                  "TRAT1",
                  "MAF",
                  "ITK")

#Markers for t-cell figure for report
t.cell.figure.221216 <- c("CD247",
                          "CD3D",
                          "CD3E",
                          "TARP",
                          "LOC121110951",
                          "TRBV6-5",
                          "CD4",
                          "CD8A",
                          "CD8BP",
                          "TCF7",
                          "BCL11B",
                          "CBLB",
                          "MAF",
                          "SOX13",
                          "GATA3",
                          "KK34",
                          "RUNX1",
                          "MYB",
                          "INPP5A",
                          "PTPN14",
                          "GNLY",
                          "FASLG",
                          "GZMA",
                          "GZMM",
                          "IL20RA",
                          "CD226",
                          "IL2RB",
                          "ADCY7",
                          "SATB1",
                          "THEMIS",
                          "CD28",
                          "TOX",
                          "IL7R",
                          "RORA",
                          "IL2RA",
                          "IL18R1",
                          "CTLA4",
                          "SMAD7",
                          "TPT1",
                          "HS6ST3",
                          "KCNQ1",
                          "FHIT",
                          "WWOX",
                          "UBE2E2",
                          "FMN1",
                          "ST3GAL1")
#marekrs for monocyte figure, for report
mono.figure.221230 <- c("CD74",
                        "BLB1",
                        "BLB2",
                        "MMR1L4",
                        "MMP9",
                        "PPARG",
                        "OSBPL3",
                        "S100A12",
                        "SPINK2",
                        "C1QC",
                        "CD55",
                        "LOC121107581",
                        "SAA",
                        "CD81",
                        "J6367-mgp02",
                        "SLC16A7",
                        "ALCAM",
                        "BF1",
                        "BF2",
                        "CD88",
                        "TLR4",
                        "TLR7",
                        "TLR2A",
                        "TLR1B",
                        "TRAF3",
                        "CD14",
                        "CCR5",
                        "IL1R2",
                        "LOC395551",
                        "IL8L1",
                        "IL8L2",
                        "IL1B",
                        "IL18",
                        "BHLHE40",
                        "NR4A3",
                        "CD83",
                        "INHBA", #from shah, DC 
                        "ARHGAP22",
                        "RASGEF1B",
                        "DCLK3",
                        "HTRA1",
                        "CSF1R",
                        "CSF2R",
                        "FCER1G",
                        "DOCK4",
                        "FLT3", #other DC
                        #                        "XCR1",
                        "CIITA", # not  DC specific
                        "ZBTB46",
                        "ID2",
                        "IRF8",
                        "CADM1")
#markers for b-cell figure for report
b.cell.fig.221207 <- c("EBF1",
                       "PAX5",
                       "IGLL1",
                       "CXCR4",
                       "HMGB1",
                       "LAMP3"
                       , "CD79B"
                       , "LOC396098" #BU-1
                       , "CD74"
                       , "BLB1",
                       #                       "PAX5", #shah
                       #      "LOC396098",
                       "LOC419333",
                       "BLVRA",
                       #       "TNFRSF13C",
                       "SCG5",
                       "CD1C",
                       "WDR66",
                       "SOX5",#late stage
                       "TBX21",
                       "JCHAIN",#plasma
                       "PRDM1", #blimp1
                       "TNFRSF13C" #BAFFR
)

b.cell.figure.230112 <- c("LOC396098",
                          "LOC121108878",
                          "CD79B",
                          "IGLL1",
                          "VH26L1",
                          "EVI2A",
                          "VAV2",
                          "LYN",
                          "PAX5",
                          "EBF1",
                          "TCF4",
                          "SOX5",
                          "BLB1",
                          "BLB2",
                          "CD74",
                          "IRAG2",
                          "MARCH8",
                          "BHLHE41",
                          "PTPRJ",
                          "BANK1",
                          "MAML3",
                          "CXCR4",
                          "TNFSF13B",
                          "TNFRSF13C",
                          "HMGB1",
                          "ATP11A",
                          "FNIP1",
                          "IL5RA",
                          "TLR1A",
                          "CD83",
                          "LOC395551",
                          "OIT3",
                          "MYLIP",
                          "WWOX",
                          "FHIT")

prol <- c("IGLL1",
          "VH26L1",
          "JCHAIN",
          "GNLY",
          "J6367-mgp01",
          "PPIA",
          "LOC100859737",
          "HMGB1",
          "GZMA",
          "LOC427882")

#markers for general figure report
stora.fig <- c("LOC396098","SOX5","PAX5","CD3E","CD3D","TARP","CD4","CD8A","CD8BP","MMR1L4","ITGA2B","ITGB3","HBBA")

#markers to use for plots in excels
bcellfeats <- c("EBF1", "PAX5", "IGLL1", "CXCR4","TNFSF13B","HMGB1", "LAMP3", "CD79B","JCHAIN", "PRDM1", "TNFRSF13C", "LOC396098", "CD74", "BLB1", "SOX5")
tcellfeats <- c("TARP","TRBV6-5","TCF7","ITK","TRAT1","CTLA4","CD4","CD8A","CD8BP","IL2RA","FASLG","MKI67","CCR7","CX3CR1","CD247","CD28","CD7","CD3E","CD3D")
monocytefeats <- unique(c(c("BLB2","BLB1","CD74","MMR1L4","MMP9","LOC35551","IL1B","IL8L2","IL8L","IL18","SPINK2","S100a12","TLR4","TLR7","CD14","CCR5","TLR2A","TLR1B"),c("PPARG","SAMSN1","C1QC","CD55","CCR5","SPINK2","S100A12","J6367-mgp02")))
all_subset_marks <- c("MMR1L4","LOC396098", "IGLL1","BLB1","TARP","CD8A","CD4","ITGA2B","ITGB3","GATA2","ATP11A","SOX5","HBBA","MKI67")
